/*
 * CodeHighlighter - a JavaScript library to highlight Code as in Notepad++
 * Copyright (C) 2015  Michael David Kuckuk
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */

$.fn.highlightCode = function(codeType) {
	var self = this;
	var functions = {
		html: function() {
			var code = self.html();
			var HtmlRegex = /(\&lt;[a-zA-Z1-6]+(\s*[a-zA-Z1-6\-_\.]+(?:=\".*\")?)*\s*\/?\s*\&gt;)/g;
			var HtmlRegex2 = /\&lt;[a-zA-Z1-6]+(\s*[a-zA-Z1-6\-_\.]+(?:=\".*\")?)*\s*\/?\s*\&gt;/g;
			var HtmlEndRegex = /(\&lt;\/[a-zA-Z1-6]*\&gt;)/g;
			var attributeRegex = /([a-zA-Z0-9\-\_]*)=(\"[a-zA-Z0-9\-\_\s\{\}\(\)\[\]\.\/\,\=\+\#]*\")/g;
			var commentRegex1 = /(&lt;!--[\s\S]*?--&gt;)/g;
			var commentRegex2 = /(\/\/.*)/g;
			var styleRegex = /&lt;style&gt;([\s\S]*?)&lt;\/style&gt;/g
			var scriptRegex = /&lt;script&gt;([\s\S]*?)&lt;\/script&gt;/g
			
			var result = code;
			
			result = result.replace(/</g, '&lt;');
			result = result.replace(/>/g, '&gt;');
			console.log(result);
			
			result = result.replace(HtmlRegex, '<span class="htmlTag">$1</span>');
			
			var htmlAttrMatches = result.match(HtmlRegex2);
			for(var i = 0; i < htmlAttrMatches.length; i++) {
				var attrs = htmlAttrMatches[i];
				
				attrs = attrs.replace(attributeRegex, '<span class="htmlAttr">$1</span>=<span class="htmlValue">$2</span>');
				
				result = result.replace(htmlAttrMatches[i], attrs);
			}
			
			result = result.replace(HtmlEndRegex, '<span class="htmlTag">$1</span>');
			result = result.replace(commentRegex1, '<span class="comment">$1</span>');
			result = result.replace(commentRegex2, '<span class="comment">$1</span>');
			
			result = result.replace(/\n/g, '<br />');
			result = result.replace(/\t/g, '&nbsp;&nbsp;&nbsp;&nbsp;');
			
			console.log(result);
			return result;
		},
		
		css: function() {
			var result = self.html();
			
			var attrsRegex = /{((?:\s*[a-zA-Z0-9\-\_]*\s*:\s*[a-zA-Z0-9\-\_\%\s\!\(\)\.\#\,\"\'\/\*]*;\s*)+)}/g;
			var attrNameRegex = /(\{|\;|\>)(\s*[a-zA-Z0-9\-\_]+\s*)/g;
			
			var selectorRegex = /(?:}|^)([\s\S]*?){/g;
			var idRegex = /\#([a-zA-Z0-9\.\-\_]*)/g;
			var classRegex = /\.([a-zA-Z0-9\.\-\_]*)/g;
			var pseudoclassRegex = /\:([a-zA-Z0-9\.\-\_]*)/g;
			var tagRegex = /((?:}|\s)+)([a-zA-Z0-9\-\_]+)/g;
			
			var commentRegex = /(\/\*[\s\S]*?\*\/)/g;
			
			result = result.replace(/</g, '&lt;');
			result = result.replace(/>/g, '&gt;');
			
			result = result.replace(attrNameRegex, '$1<span class="cssAttr">$2</span>');
			
			var selectorMatches = result.match(selectorRegex);
			for(var i = 0; i < selectorMatches.length; i++) {
				var selector = selectorMatches[i];
				selector = selector.replace(tagRegex, '$1<span class="cssTag">$2</span>');
				selector = selector.replace(pseudoclassRegex, ':<span class="cssPseudoClass">$1</span>');
				selector = selector.replace(idRegex, '#<span class="cssId">$1</span>');
				selector = selector.replace(classRegex, '.<span class="cssClass">$1</span>');
				result = result.replace(selectorMatches[i], selector);
			}
			
			result = result.replace(/(\!important)/g, '<span class="cssImportant">$1</span>');
			result = result.replace(commentRegex, '<span class="comment">$1</span>');
			
			result = result.replace(/\n/g, '<br />');
			result = result.replace(/\t/g, '&nbsp;&nbsp;&nbsp;&nbsp;');
			
			return result;
		},
		
		js: function() {
			var result = self.html();
			console.log(result);
			
			var intRegex = /(\W)(\d+)(\W)/g;
			var commentRegex1 = /(\/\*[\s\S]*?\*\/)/g;
			var commentRegex2 = /(\/\/.*)/g;
			var quoteRegex1 = /([^\\])(\".*?[^\\]\")/g;
			var quoteRegex2 = /([^\\])(\'.*?[^\\]\')/g;
			var regexRegex = /(\/[^\n\>\<\/]+\/g?i?m?)/g;
			
			var jsKeywords = [
				/(\W)(class)([^\w\=\"])/g,
				/(\W)(function)(\W)/g,
				/(\W)(var)(\W)/g,
				/(\W)(switch)(\W)/g,
				/(\W)(case)(\W)/g,
				/(\W)(break)(\W)/g,
				/(\W)(default)(\W)/g,
				/(\W)(for)(\W)/g,
				/(\W)(if)(\W)/g,
				/(\W)(else)(\W)/g,
				/(\W)(do)(\W)/g,
				/(\W)(while)(\W)/g,
				/(\W)(typeof)(\W)/g,
				/(\W)(return)(\W)/g,
				/(\W)(this)(\W)/g,
				/(\W)(true)(\W)/g,
				/(\W)(abstract)(\W)/g,
				/(\W)(arguments)(\W)/g,
				/(\W)(boolean)(\W)/g,
				/(\W)(byte)(\W)/g,
				/(\W)(catch)(\W)/g,
				/(\W)(char)(\W)/g,
				/(\W)(const)(\W)/g,
				/(\W)(continue)(\W)/g,
				/(\W)(debugger)(\W)/g,
				/(\W)(delete)(\W)/g,
				/(\W)(double)(\W)/g,
				/(\W)(enum)(\W)/g,
				/(\W)(eval)(\W)/g,
				/(\W)(export)(\W)/g,
				/(\W)(extends)(\W)/g,
				/(\W)(final)(\W)/g,
				/(\W)(finally)(\W)/g,
				/(\W)(float)(\W)/g,
				/(\W)(goto)(\W)/g,
				/(\W)(implements)(\W)/g,
				/(\W)(import)(\W)/g,
				/(\W)(in)(\W)/g,
				/(\W)(instanceof)(\W)/g,
				/(\W)(int)(\W)/g,
				/(\W)(interface)(\W)/g,
				/(\W)(let)(\W)/g,
				/(\W)(long)(\W)/g,
				/(\W)(native)(\W)/g,
				/(\W)(new)(\W)/g,
				/(\W)(null)(\W)/g,
				/(\W)(package)(\W)/g,
				/(\W)(private)(\W)/g,
				/(\W)(protected)(\W)/g,
				/(\W)(public)(\W)/g,
				/(\W)(short)(\W)/g,
				/(\W)(static)(\W)/g,
				/(\W)(super)(\W)/g,
				/(\W)(synchronized)(\W)/g,
				/(\W)(throw)(\W)/g,
				/(\W)(throws)(\W)/g,
				/(\W)(transient)(\W)/g,
				/(\W)(try)(\W)/g,
				/(\W)(void)(\W)/g,
				/(\W)(volatile)(\W)/g,
				/(\W)(with)(\W)/g,
				/(\W)(yield)(\W)/g,
				/(\W)(false)(\W)/g
			];
			
			console.log(result);
			result = result.replace(/</g, '&lt;');
			result = result.replace(/>/g, '&gt;');
			
			console.log(result);
			result = result.replace(quoteRegex1, '$1<span class="jsString">$2</span>');
			console.log(result);
			result = result.replace(quoteRegex2, '$1<span class="jsString">$2</span>');
			console.log(result);
			
			for(var i = 0; i < jsKeywords.length && i <= 100; i++) {
				result = result.replace(jsKeywords[i], '$1<span class="jsKeyword">$2</span>$3');
			}
			console.log(result);
			
			result = result.replace(intRegex, '$1<span class="jsInt">$2</span>$3');
			result = result.replace(commentRegex1, '<span class="comment">$1</span>');
			result = result.replace(commentRegex2, '<span class="comment">$1</span>');
			
			result = result.replace(/\n/g, '<br />');
			result = result.replace(/\t/g, '&nbsp;&nbsp;&nbsp;&nbsp;');
			
			return result;
		},
		
		php: function() {
			var result = self.html();
			console.log(result);
			
			var intRegex = /(\W)(\d+)(\W)/g;
			var commentRegex1 = /(\/\*[\s\S]*?\*\/)/g;
			var commentRegex2 = /(\/\/.*)/g;
			var stringRegex1 = /([^\\])(\".*?[^\\]\")/g;
			var stringRegex2 = /([^\\])(\'.*?[^\\]\')/g;
			var phpStartRegex = /(&lt;\?php)/g;
			var phpEndRegex = /(\?&gt;)/g;
			var phpVarRegex = /(\$\w+)/g
			
			var phpKeywords = [
				/(\W)(class)([^\w\=\"])/g,
				/(\W)(filesize)(\W)/g,
				/(\W)(filemtime)(\W)/g,
				/(\W)(ksort)(\W)/g,
				/(\W)(sort)(\W)/g,
				/(\W)(count)(\W)/g,
				/(\W)(shell_exec)(\W)/g,
				/(\W)(disk_free_space)(\W)/g,
				/(\W)(disk_total_space)(\W)/g,
				/(\W)(file_exists)(\W)/g,
				/(\W)(strip_tags)(\W)/g,
				/(\W)(htmlentities)(\W)/g,
				/(\W)(stripslashes)(\W)/g,
				/(\W)(mysql_real_escape_string)(\W)/g,
				/(\W)(session_start)(\W)/g,
				/(\W)(error_reporting)(\W)/g,
				/(\W)(define)(\W)/g,
				/(\W)(srt_replace)(\W)/g,
				/(\W)(pathinfo)(\W)/g,
				/(\W)(date)(\W)/g,
				/(\W)(time)(\W)/g,
				/(\W)(version_compare)(\W)/g,
				/(\W)(sha1)(\W)/g,
				/(\W)(sha1_file)(\W)/g,
				/(\W)(md5)(\W)/g,
				/(\W)(md5_file)(\W)/g,
				/(\W)(ignore_user_abort)(\W)/g,
				/(\W)(and)(\W)/g,
				/(\W)(or)(\W)/g,
				/(\W)(xor)(\W)/g,
				/(\W)(__dir__)(\W)/g,
				/(\W)(__method__)(\W)/g,
				/(\W)(__namespace__)(\W)/g,
				/(\W)(__file__)(\W)/g,
				/(\W)(__line__)(\W)/g,
				/(\W)(array)(\W)/g,
				/(\W)(as)(\W)/g,
				/(\W)(break)(\W)/g,
				/(\W)(case)(\W)/g,
				/(\W)(cfunction)(\W)/g,
				/(\W)(const)(\W)/g,
				/(\W)(continue)(\W)/g,
				/(\W)(declare)(\W)/g,
				/(\W)(default)(\W)/g,
				/(\W)(die)(\W)/g,
				/(\W)(do)(\W)/g,
				/(\W)(echo)(\W)/g,
				/(\W)(else)(\W)/g,
				/(\W)(elseif)(\W)/g,
				/(\W)(empty)(\W)/g,
				/(\W)(enddeclare)(\W)/g,
				/(\W)(endfor)(\W)/g,
				/(\W)(endforeach)(\W)/g,
				/(\W)(endif)(\W)/g,
				/(\W)(endswitch)(\W)/g,
				/(\W)(endwhile)(\W)/g,
				/(\W)(eval)(\W)/g,
				/(\W)(exit)(\W)/g,
				/(\W)(extends)(\W)/g,
				/(\W)(for)(\W)/g,
				/(\W)(foreach)(\W)/g,
				/(\W)(function)(\W)/g,
				/(\W)(global)(\W)/g,
				/(\W)(if)(\W)/g,
				/(\W)(include)(\W)/g,
				/(\W)(include_once)(\W)/g,
				/(\W)(isset)(\W)/g,
				/(\W)(list)(\W)/g,
				/(\W)(new)(\W)/g,
				/(\W)(old_function)(\W)/g,
				/(\W)(print)(\W)/g,
				/(\W)(require)(\W)/g,
				/(\W)(require_once)(\W)/g,
				/(\W)(return)(\W)/g,
				/(\W)(static)(\W)/g,
				/(\W)(switch)(\W)/g,
				/(\W)(unset)(\W)/g,
				/(\W)(use)(\W)/g,
				/(\W)(var)(\W)/g,
				/(\W)(while)(\W)/g,
				/(\W)(__function__)(\W)/g,
				/(\W)(__class__)(\W)/g,
				/(\W)(php_version)(\W)/g,
				/(\W)(php_os)(\W)/g,
				/(\W)(default_include_path)(\W)/g,
				/(\W)(pear_install_dir)(\W)/g,
				/(\W)(pear_extension_dir)(\W)/g,
				/(\W)(php_extension_dir)(\W)/g,
				/(\W)(php_bindir)(\W)/g,
				/(\W)(php_libdir)(\W)/g,
				/(\W)(php_datadir)(\W)/g,
				/(\W)(php_sysconfdir)(\W)/g,
				/(\W)(php_localstatedir)(\W)/g,
				/(\W)(php_config_file_path)(\W)/g,
				/(\W)(php_output_handler_start)(\W)/g,
				/(\W)(php_output_handler_cont)(\W)/g,
				/(\W)(php_output_handler_end)(\W)/g,
				/(\W)(e_error)(\W)/g,
				/(\W)(e_warning)(\W)/g,
				/(\W)(e_parse)(\W)/g,
				/(\W)(e_notice)(\W)/g,
				/(\W)(e_core_error)(\W)/g,
				/(\W)(e_core_warning)(\W)/g,
				/(\W)(e_compile_error)(\W)/g,
				/(\W)(e_compile_warning)(\W)/g,
				/(\W)(e_user_error)(\W)/g,
				/(\W)(e_user_warning)(\W)/g,
				/(\W)(e_user_notice)(\W)/g,
				/(\W)(e_all)(\W)/g,
				/(\W)(true)(\W)/g,
				/(\W)(false)(\W)/g,
				/(\W)(bool)(\W)/g,
				/(\W)(boolean)(\W)/g,
				/(\W)(int)(\W)/g,
				/(\W)(integer)(\W)/g,
				/(\W)(float)(\W)/g,
				/(\W)(double)(\W)/g,
				/(\W)(real)(\W)/g,
				/(\W)(string)(\W)/g,
				/(\W)(array)(\W)/g,
				/(\W)(object)(\W)/g,
				/(\W)(resource)(\W)/g,
				/(\W)(null)(\W)/g,
				/(\W)(extends)(\W)/g,
				/(\W)(parent)(\W)/g,
				/(\W)(stdclass)(\W)/g,
				/(\W)(directory)(\W)/g,
				/(\W)(__sleep)(\W)/g,
				/(\W)(__wakeup)(\W)/g,
				/(\W)(interface)(\W)/g,
				/(\W)(implements)(\W)/g,
				/(\W)(abstract)(\W)/g,
				/(\W)(public)(\W)/g,
				/(\W)(protected)(\W)/g,
				/(\W)(private)(\W)/g,
				/(\W)(printf)(\W)/g,
				/(\W)(print_r)(\W)/g,
				/(\W)(php_major_version)(\W)/g,
				/(\W)(php_minor_version)(\W)/g,
				/(\W)(php_release_version)(\W)/g,
				/(\W)(php_version_id)(\W)/g,
				/(\W)(php_extra_version)(\W)/g,
				/(\W)(php_zts)(\W)/g,
				/(\W)(php_debug)(\W)/g,
				/(\W)(php_maxpathlen)(\W)/g,
				/(\W)(php_sapi)(\W)/g,
				/(\W)(php_eol)(\W)/g,
				/(\W)(php_int_max)(\W)/g,
				/(\W)(php_int_size)(\W)/g,
				/(\W)(php_prefix)(\W)/g,
				/(\W)(php_mandir)(\W)/g,
				/(\W)(php_config_file_scan_dir)(\W)/g,
				/(\W)(php_shlib_suffix)(\W)/g,
				/(\W)(php_windows_version_major)(\W)/g,
				/(\W)(php_windows_version_minor)(\W)/g,
				/(\W)(php_windows_version_build)(\W)/g,
				/(\W)(php_windows_version_platform)(\W)/g,
				/(\W)(php_windows_version_sp_major)(\W)/g,
				/(\W)(php_windows_version_sp_minor)(\W)/g,
				/(\W)(php_windows_version_suitemask)(\W)/g,
				/(\W)(php_windows_version_producttype)(\W)/g,
				/(\W)(php_windows_nt_domain_controller)(\W)/g,
				/(\W)(php_windows_nt_server)(\W)/g,
				/(\W)(php_windows_nt_workstation)(\W)/g,
				/(\W)(e_deprecated)(\W)/g,
				/(\W)(e_user_deprecated)(\W)/g,
				/(\W)(e_strict)(\W)/g,
				/(\W)(__compiler_halt_offset__)(\W)/g,
				/(\W)(extr_overwrite)(\W)/g,
				/(\W)(extr_skip)(\W)/g,
				/(\W)(extr_prefix_same)(\W)/g,
				/(\W)(extr_prefix_all)(\W)/g,
				/(\W)(extr_prefix_invalid)(\W)/g,
				/(\W)(extr_prefix_if_exists)(\W)/g,
				/(\W)(extr_if_exists)(\W)/g,
				/(\W)(sort_asc)(\W)/g,
				/(\W)(sort_desc)(\W)/g,
				/(\W)(sort_regular)(\W)/g,
				/(\W)(sort_numeric)(\W)/g,
				/(\W)(sort_string)(\W)/g,
				/(\W)(case_lower)(\W)/g,
				/(\W)(case_upper)(\W)/g,
				/(\W)(count_normal)(\W)/g,
				/(\W)(count_recursive)(\W)/g,
				/(\W)(assert_active)(\W)/g,
				/(\W)(assert_callback)(\W)/g,
				/(\W)(assert_bail)(\W)/g,
				/(\W)(assert_warning)(\W)/g,
				/(\W)(assert_quiet_eval)(\W)/g,
				/(\W)(connection_aborted)(\W)/g,
				/(\W)(connection_normal)(\W)/g,
				/(\W)(connection_timeout)(\W)/g,
				/(\W)(ini_user)(\W)/g,
				/(\W)(ini_perdir)(\W)/g,
				/(\W)(ini_system)(\W)/g,
				/(\W)(ini_all)(\W)/g,
				/(\W)(m_e)(\W)/g,
				/(\W)(m_log2e)(\W)/g,
				/(\W)(m_log10e)(\W)/g,
				/(\W)(m_ln2)(\W)/g,
				/(\W)(m_ln10)(\W)/g,
				/(\W)(m_pi)(\W)/g,
				/(\W)(m_pi_2)(\W)/g,
				/(\W)(m_pi_4)(\W)/g,
				/(\W)(m_1_pi)(\W)/g,
				/(\W)(m_2_pi)(\W)/g,
				/(\W)(m_2_sqrtpi)(\W)/g,
				/(\W)(m_sqrt2)(\W)/g,
				/(\W)(m_sqrt1_2)(\W)/g,
				/(\W)(crypt_salt_length)(\W)/g,
				/(\W)(crypt_std_des)(\W)/g,
				/(\W)(crypt_ext_des)(\W)/g,
				/(\W)(crypt_md5)(\W)/g,
				/(\W)(crypt_blowfish)(\W)/g,
				/(\W)(directory_separator)(\W)/g,
				/(\W)(seek_set)(\W)/g,
				/(\W)(seek_cur)(\W)/g,
				/(\W)(seek_end)(\W)/g,
				/(\W)(lock_sh)(\W)/g,
				/(\W)(lock_ex)(\W)/g,
				/(\W)(lock_un)(\W)/g,
				/(\W)(lock_nb)(\W)/g,
				/(\W)(html_specialchars)(\W)/g,
				/(\W)(html_entities)(\W)/g,
				/(\W)(ent_compat)(\W)/g,
				/(\W)(ent_quotes)(\W)/g,
				/(\W)(ent_noquotes)(\W)/g,
				/(\W)(info_general)(\W)/g,
				/(\W)(info_credits)(\W)/g,
				/(\W)(info_configuration)(\W)/g,
				/(\W)(info_modules)(\W)/g,
				/(\W)(info_environment)(\W)/g,
				/(\W)(info_variables)(\W)/g,
				/(\W)(info_license)(\W)/g,
				/(\W)(info_all)(\W)/g,
				/(\W)(credits_group)(\W)/g,
				/(\W)(credits_general)(\W)/g,
				/(\W)(credits_sapi)(\W)/g,
				/(\W)(credits_modules)(\W)/g,
				/(\W)(credits_docs)(\W)/g,
				/(\W)(credits_fullpage)(\W)/g,
				/(\W)(credits_qa)(\W)/g,
				/(\W)(credits_all)(\W)/g,
				/(\W)(str_pad_left)(\W)/g,
				/(\W)(str_pad_right)(\W)/g,
				/(\W)(str_pad_both)(\W)/g,
				/(\W)(pathinfo_dirname)(\W)/g,
				/(\W)(pathinfo_basename)(\W)/g,
				/(\W)(pathinfo_extension)(\W)/g,
				/(\W)(path_separator)(\W)/g,
				/(\W)(char_max)(\W)/g,
				/(\W)(lc_ctype)(\W)/g,
				/(\W)(lc_numeric)(\W)/g,
				/(\W)(lc_time)(\W)/g,
				/(\W)(lc_collate)(\W)/g,
				/(\W)(lc_monetary)(\W)/g,
				/(\W)(lc_all)(\W)/g,
				/(\W)(lc_messages)(\W)/g,
				/(\W)(abday_1)(\W)/g,
				/(\W)(abday_2)(\W)/g,
				/(\W)(abday_3)(\W)/g,
				/(\W)(abday_4)(\W)/g,
				/(\W)(abday_5)(\W)/g,
				/(\W)(abday_6)(\W)/g,
				/(\W)(abday_7)(\W)/g,
				/(\W)(day_1)(\W)/g,
				/(\W)(day_2)(\W)/g,
				/(\W)(day_3)(\W)/g,
				/(\W)(day_4)(\W)/g,
				/(\W)(day_5)(\W)/g,
				/(\W)(day_6)(\W)/g,
				/(\W)(day_7)(\W)/g,
				/(\W)(abmon_1)(\W)/g,
				/(\W)(abmon_2)(\W)/g,
				/(\W)(abmon_3)(\W)/g,
				/(\W)(abmon_4)(\W)/g,
				/(\W)(abmon_5)(\W)/g,
				/(\W)(abmon_6)(\W)/g,
				/(\W)(abmon_7)(\W)/g,
				/(\W)(abmon_8)(\W)/g,
				/(\W)(abmon_9)(\W)/g,
				/(\W)(abmon_10)(\W)/g,
				/(\W)(abmon_11)(\W)/g,
				/(\W)(abmon_12)(\W)/g,
				/(\W)(mon_1)(\W)/g,
				/(\W)(mon_2)(\W)/g,
				/(\W)(mon_3)(\W)/g,
				/(\W)(mon_4)(\W)/g,
				/(\W)(mon_5)(\W)/g,
				/(\W)(mon_6)(\W)/g,
				/(\W)(mon_7)(\W)/g,
				/(\W)(mon_8)(\W)/g,
				/(\W)(mon_9)(\W)/g,
				/(\W)(mon_10)(\W)/g,
				/(\W)(mon_11)(\W)/g,
				/(\W)(mon_12)(\W)/g,
				/(\W)(am_str)(\W)/g,
				/(\W)(pm_str)(\W)/g,
				/(\W)(d_t_fmt)(\W)/g,
				/(\W)(d_fmt)(\W)/g,
				/(\W)(t_fmt)(\W)/g,
				/(\W)(t_fmt_ampm)(\W)/g,
				/(\W)(era)(\W)/g,
				/(\W)(era_year)(\W)/g,
				/(\W)(era_d_t_fmt)(\W)/g,
				/(\W)(era_d_fmt)(\W)/g,
				/(\W)(era_t_fmt)(\W)/g,
				/(\W)(alt_digits)(\W)/g,
				/(\W)(int_curr_symbol)(\W)/g,
				/(\W)(currency_symbol)(\W)/g,
				/(\W)(crncystr)(\W)/g,
				/(\W)(mon_decimal_point)(\W)/g,
				/(\W)(mon_thousands_sep)(\W)/g,
				/(\W)(mon_grouping)(\W)/g,
				/(\W)(positive_sign)(\W)/g,
				/(\W)(negative_sign)(\W)/g,
				/(\W)(int_frac_digits)(\W)/g,
				/(\W)(frac_digits)(\W)/g,
				/(\W)(p_cs_precedes)(\W)/g,
				/(\W)(p_sep_by_space)(\W)/g,
				/(\W)(n_cs_precedes)(\W)/g,
				/(\W)(n_sep_by_space)(\W)/g,
				/(\W)(p_sign_posn)(\W)/g,
				/(\W)(n_sign_posn)(\W)/g,
				/(\W)(decimal_point)(\W)/g,
				/(\W)(radixchar)(\W)/g,
				/(\W)(thousands_sep)(\W)/g,
				/(\W)(thousep)(\W)/g,
				/(\W)(grouping)(\W)/g,
				/(\W)(yesexpr)(\W)/g,
				/(\W)(noexpr)(\W)/g,
				/(\W)(yesstr)(\W)/g,
				/(\W)(nostr)(\W)/g,
				/(\W)(codeset)(\W)/g,
				/(\W)(log_emerg)(\W)/g,
				/(\W)(log_alert)(\W)/g,
				/(\W)(log_crit)(\W)/g,
				/(\W)(log_err)(\W)/g,
				/(\W)(log_warning)(\W)/g,
				/(\W)(log_notice)(\W)/g,
				/(\W)(log_info)(\W)/g,
				/(\W)(log_debug)(\W)/g,
				/(\W)(log_kern)(\W)/g,
				/(\W)(log_user)(\W)/g,
				/(\W)(log_mail)(\W)/g,
				/(\W)(log_daemon)(\W)/g,
				/(\W)(log_auth)(\W)/g,
				/(\W)(log_syslog)(\W)/g,
				/(\W)(log_lpr)(\W)/g,
				/(\W)(log_news)(\W)/g,
				/(\W)(log_uucp)(\W)/g,
				/(\W)(log_cron)(\W)/g,
				/(\W)(log_authpriv)(\W)/g,
				/(\W)(log_local0)(\W)/g,
				/(\W)(log_local1)(\W)/g,
				/(\W)(log_local2)(\W)/g,
				/(\W)(log_local3)(\W)/g,
				/(\W)(log_local4)(\W)/g,
				/(\W)(log_local5)(\W)/g,
				/(\W)(log_local6)(\W)/g,
				/(\W)(log_local7)(\W)/g,
				/(\W)(log_pid)(\W)/g,
				/(\W)(log_cons)(\W)/g,
				/(\W)(log_odelay)(\W)/g,
				/(\W)(log_ndelay)(\W)/g,
				/(\W)(log_nowait)(\W)/g,
				/(\W)(log_perror)(\W)/g,
				/(\W)(msql_connect)(\W)/g,
				/(\W)(msql_close)(\W)/g,
				/(\W)(msql)(\W)/g,
				/(\W)(msql_create_db)(\W)/g,
				/(\W)(msql_createdb)(\W)/g,
				/(\W)(msql_drop_db)(\W)/g,
				/(\W)(msql_drop_db)(\W)/g,
				/(\W)(msql_select_db)(\W)/g,
				/(\W)(msql_select_db)(\W)/g,
				/(\W)(msql_pconnect)(\W)/g,
				/(\W)(msql)(\W)/g,
				/(\W)(msql_create_db)(\W)/g,
				/(\W)(msql_createdb)(\W)/g,
				/(\W)(msql_drop_db)(\W)/g,
				/(\W)(msql_drop_db)(\W)/g,
				/(\W)(msql_select_db)(\W)/g,
				/(\W)(msql_select_db)(\W)/g,
				/(\W)(msql_db_query)(\W)/g,
				/(\W)(msql_list_dbs)(\W)/g,
				/(\W)(msql_list_fields)(\W)/g,
				/(\W)(msql_list_tables)(\W)/g,
				/(\W)(msql_query)(\W)/g,
				/(\W)(msql)(\W)/g,
				/(\W)(msql_affected_rows)(\W)/g,
				/(\W)(msql_data_seek)(\W)/g,
				/(\W)(msql_dbname)(\W)/g,
				/(\W)(msql_fetch_array)(\W)/g,
				/(\W)(msql_fetch_field)(\W)/g,
				/(\W)(msql_fetch_object)(\W)/g,
				/(\W)(msql_fetch_row)(\W)/g,
				/(\W)(msql_field_seek)(\W)/g,
				/(\W)(msql_field_table)(\W)/g,
				/(\W)(msql_field_flags)(\W)/g,
				/(\W)(msql_field_len)(\W)/g,
				/(\W)(msql_field_name)(\W)/g,
				/(\W)(msql_field_type)(\W)/g,
				/(\W)(msql_num_fields)(\W)/g,
				/(\W)(msql_num_rows)(\W)/g,
				/(\W)(msql_numfields)(\W)/g,
				/(\W)(msql_numrows)(\W)/g,
				/(\W)(msql_result)(\W)/g,
				/(\W)(mssql_connect)(\W)/g,
				/(\W)(mssql_query)(\W)/g,
				/(\W)(mssql_select_db)(\W)/g,
				/(\W)(mssql_close)(\W)/g,
				/(\W)(mssql_pconnect)(\W)/g,
				/(\W)(mssql_query)(\W)/g,
				/(\W)(mssql_select_db)(\W)/g,
				/(\W)(mssql_query)(\W)/g,
				/(\W)(mssql_data_seek)(\W)/g,
				/(\W)(mssql_fetch_array)(\W)/g,
				/(\W)(mssql_fetch_field)(\W)/g,
				/(\W)(mssql_fetch_object)(\W)/g,
				/(\W)(mssql_fetch_row)(\W)/g,
				/(\W)(mssql_field_length)(\W)/g,
				/(\W)(mssql_field_name)(\W)/g,
				/(\W)(mssql_field_seek)(\W)/g,
				/(\W)(mssql_field_type)(\W)/g,
				/(\W)(mssql_num_fields)(\W)/g,
				/(\W)(mssql_num_rows)(\W)/g,
				/(\W)(mssql_result)(\W)/g,
				/(\W)(mssql_free_result)(\W)/g,
				/(\W)(mysql_connect)(\W)/g,
				/(\W)(mysql_affected_rows)(\W)/g,
				/(\W)(mysql_change_user)(\W)/g,
				/(\W)(mysql_create_db)(\W)/g,
				/(\W)(mysql_data_seek)(\W)/g,
				/(\W)(mysql_db_name)(\W)/g,
				/(\W)(mysql_db_query)(\W)/g,
				/(\W)(mysql_drop_db)(\W)/g,
				/(\W)(mysql_errno)(\W)/g,
				/(\W)(mysql_error)(\W)/g,
				/(\W)(mysql_insert_id)(\W)/g,
				/(\W)(mysql_list_dbs)(\W)/g,
				/(\W)(mysql_list_fields)(\W)/g,
				/(\W)(mysql_list_tables)(\W)/g,
				/(\W)(mysql_query)(\W)/g,
				/(\W)(mysql_result)(\W)/g,
				/(\W)(mysql_select_db)(\W)/g,
				/(\W)(mysql_tablename)(\W)/g,
				/(\W)(mysql_get_host_info)(\W)/g,
				/(\W)(mysql_get_proto_info)(\W)/g,
				/(\W)(mysql_get_server_info)(\W)/g,
				/(\W)(mysql_close)(\W)/g,
				/(\W)(mysql_pconnect)(\W)/g,
				/(\W)(mysql_affected_rows)(\W)/g,
				/(\W)(mysql_change_user)(\W)/g,
				/(\W)(mysql_create_db)(\W)/g,
				/(\W)(mysql_data_seek)(\W)/g,
				/(\W)(mysql_db_name)(\W)/g,
				/(\W)(mysql_db_query)(\W)/g,
				/(\W)(mysql_drop_db)(\W)/g,
				/(\W)(mysql_errno)(\W)/g,
				/(\W)(mysql_error)(\W)/g,
				/(\W)(mysql_insert_id)(\W)/g,
				/(\W)(mysql_list_dbs)(\W)/g,
				/(\W)(mysql_list_fields)(\W)/g,
				/(\W)(mysql_list_tables)(\W)/g,
				/(\W)(mysql_query)(\W)/g,
				/(\W)(mysql_result)(\W)/g,
				/(\W)(mysql_select_db)(\W)/g,
				/(\W)(mysql_tablename)(\W)/g,
				/(\W)(mysql_get_host_info)(\W)/g,
				/(\W)(mysql_get_proto_info)(\W)/g,
				/(\W)(mysql_get_server_info)(\W)/g,
				/(\W)(mysql_db_query)(\W)/g,
				/(\W)(mysql_list_dbs)(\W)/g,
				/(\W)(mysql_list_fields)(\W)/g,
				/(\W)(mysql_list_processes)(\W)/g,
				/(\W)(mysql_list_tables)(\W)/g,
				/(\W)(mysql_query)(\W)/g,
				/(\W)(mysql_unbuffered_query)(\W)/g,
				/(\W)(mysql_data_seek)(\W)/g,
				/(\W)(mysql_db_name)(\W)/g,
				/(\W)(mysql_fetch_array)(\W)/g,
				/(\W)(mysql_fetch_assoc)(\W)/g,
				/(\W)(mysql_fetch_field)(\W)/g,
				/(\W)(mysql_fetch_lengths)(\W)/g,
				/(\W)(mysql_fetch_object)(\W)/g,
				/(\W)(mysql_fetch_row)(\W)/g,
				/(\W)(mysql_fetch_row)(\W)/g,
				/(\W)(mysql_field_flags)(\W)/g,
				/(\W)(mysql_field_name)(\W)/g,
				/(\W)(mysql_field_len)(\W)/g,
				/(\W)(mysql_field_seek)(\W)/g,
				/(\W)(mysql_field_table)(\W)/g,
				/(\W)(mysql_field_type)(\W)/g,
				/(\W)(mysql_num_fields)(\W)/g,
				/(\W)(mysql_num_rows)(\W)/g,
				/(\W)(mysql_result)(\W)/g,
				/(\W)(mysql_tablename)(\W)/g,
				/(\W)(mysql_free_result)(\W)/g,
				/(\W)(ocilogon)(\W)/g,
				/(\W)(ociplogon)(\W)/g,
				/(\W)(ocinlogon)(\W)/g,
				/(\W)(ocicommit)(\W)/g,
				/(\W)(ociserverversion)(\W)/g,
				/(\W)(ocinewcursor)(\W)/g,
				/(\W)(ociparse)(\W)/g,
				/(\W)(ocierror)(\W)/g,
				/(\W)(ocilogoff)(\W)/g,
				/(\W)(ocinewdescriptor)(\W)/g,
				/(\W)(ocirollback)(\W)/g,
				/(\W)(ocinewdescriptor)(\W)/g,
				/(\W)(ocirowcount)(\W)/g,
				/(\W)(ocidefinebyname)(\W)/g,
				/(\W)(ocibindbyname)(\W)/g,
				/(\W)(ociexecute)(\W)/g,
				/(\W)(ocinumcols)(\W)/g,
				/(\W)(ociresult)(\W)/g,
				/(\W)(ocifetch)(\W)/g,
				/(\W)(ocifetchinto)(\W)/g,
				/(\W)(ocifetchstatement)(\W)/g,
				/(\W)(ocicolumnisnull)(\W)/g,
				/(\W)(ocicolumnname)(\W)/g,
				/(\W)(ocicolumnsize)(\W)/g,
				/(\W)(ocicolumntype)(\W)/g,
				/(\W)(ocistatementtype)(\W)/g,
				/(\W)(ocierror)(\W)/g,
				/(\W)(ocifreestatement)(\W)/g,
				/(\W)(odbc_connect)(\W)/g,
				/(\W)(odbc_autocommit)(\W)/g,
				/(\W)(odbc_commit)(\W)/g,
				/(\W)(odbc_error)(\W)/g,
				/(\W)(odbc_errormsg)(\W)/g,
				/(\W)(odbc_exec)(\W)/g,
				/(\W)(odbc_tables)(\W)/g,
				/(\W)(odbc_tableprivileges)(\W)/g,
				/(\W)(odbc_do)(\W)/g,
				/(\W)(odbc_prepare)(\W)/g,
				/(\W)(odbc_columns)(\W)/g,
				/(\W)(odbc_columnprivileges)(\W)/g,
				/(\W)(odbc_procedurecolumns)(\W)/g,
				/(\W)(odbc_specialcolumns)(\W)/g,
				/(\W)(odbc_rollback)(\W)/g,
				/(\W)(odbc_setoption)(\W)/g,
				/(\W)(odbc_gettypeinfo)(\W)/g,
				/(\W)(odbc_primarykeys)(\W)/g,
				/(\W)(odbc_foreignkeys)(\W)/g,
				/(\W)(odbc_procedures)(\W)/g,
				/(\W)(odbc_statistics)(\W)/g,
				/(\W)(odbc_close)(\W)/g,
				/(\W)(odbc_pconnect)(\W)/g,
				/(\W)(odbc_autocommit)(\W)/g,
				/(\W)(odbc_commit)(\W)/g,
				/(\W)(odbc_error)(\W)/g,
				/(\W)(odbc_errormsg)(\W)/g,
				/(\W)(odbc_exec)(\W)/g,
				/(\W)(odbc_tables)(\W)/g,
				/(\W)(odbc_tableprivileges)(\W)/g,
				/(\W)(odbc_do)(\W)/g,
				/(\W)(odbc_prepare)(\W)/g,
				/(\W)(odbc_columns)(\W)/g,
				/(\W)(odbc_columnprivileges)(\W)/g,
				/(\W)(odbc_procedurecolumns)(\W)/g,
				/(\W)(odbc_specialcolumns)(\W)/g,
				/(\W)(odbc_rollback)(\W)/g,
				/(\W)(odbc_setoption)(\W)/g,
				/(\W)(odbc_gettypeinfo)(\W)/g,
				/(\W)(odbc_primarykeys)(\W)/g,
				/(\W)(odbc_foreignkeys)(\W)/g,
				/(\W)(odbc_procedures)(\W)/g,
				/(\W)(odbc_statistics)(\W)/g,
				/(\W)(odbc_prepare)(\W)/g,
				/(\W)(odbc_binmode)(\W)/g,
				/(\W)(odbc_cursor)(\W)/g,
				/(\W)(odbc_execute)(\W)/g,
				/(\W)(odbc_fetch_into)(\W)/g,
				/(\W)(odbc_fetch_row)(\W)/g,
				/(\W)(odbc_field_name)(\W)/g,
				/(\W)(odbc_field_num)(\W)/g,
				/(\W)(odbc_field_type)(\W)/g,
				/(\W)(odbc_field_len)(\W)/g,
				/(\W)(odbc_field_precision)(\W)/g,
				/(\W)(odbc_field_scale)(\W)/g,
				/(\W)(odbc_longreadlen)(\W)/g,
				/(\W)(odbc_num_fields)(\W)/g,
				/(\W)(odbc_num_rows)(\W)/g,
				/(\W)(odbc_result)(\W)/g,
				/(\W)(odbc_result_all)(\W)/g,
				/(\W)(odbc_setoption)(\W)/g,
				/(\W)(odbc_free_result)(\W)/g,
				/(\W)(openssl_get_privatekey)(\W)/g,
				/(\W)(openssl_get_publickey)(\W)/g,
				/(\W)(openssl_sign)(\W)/g,
				/(\W)(openssl_seal)(\W)/g,
				/(\W)(openssl_open)(\W)/g,
				/(\W)(openssl_verify)(\W)/g,
				/(\W)(openssl_free_key)(\W)/g,
				/(\W)(xml_parser_create)(\W)/g,
				/(\W)(xml_parser_create_ns)(\W)/g,
				/(\W)(xml_set_object)(\W)/g,
				/(\W)(xml_set_element_handler)(\W)/g,
				/(\W)(xml_set_character_data_handler)(\W)/g,
				/(\W)(xml_set_processing_instruction_handler)(\W)/g,
				/(\W)(xml_set_default_handler)(\W)/g,
				/(\W)(xml_set_unparsed_entity_decl_handler)(\W)/g,
				/(\W)(xml_set_notation_decl_handler)(\W)/g,
				/(\W)(xml_set_external_entity_ref_handler)(\W)/g,
				/(\W)(xml_parse)(\W)/g,
				/(\W)(xml_get_error_code)(\W)/g,
				/(\W)(xml_error_string)(\W)/g,
				/(\W)(xml_get_current_line_number)(\W)/g,
				/(\W)(xml_get_current_column_number)(\W)/g,
				/(\W)(xml_get_current_byte_index)(\W)/g,
				/(\W)(xml_parse_into_struct)(\W)/g,
				/(\W)(xml_parser_set_option)(\W)/g,
				/(\W)(xml_parser_get_option)(\W)/g,
				/(\W)(xml_parser_free)(\W)/g,
				/(\W)(gzopen)(\W)/g,
				/(\W)(gzeof)(\W)/g,
				/(\W)(gzgetc)(\W)/g,
				/(\W)(gzgets)(\W)/g,
				/(\W)(gzgetss)(\W)/g,
				/(\W)(gzpassthru)(\W)/g,
				/(\W)(gzputs)(\W)/g,
				/(\W)(gzread)(\W)/g,
				/(\W)(gzrewind)(\W)/g,
				/(\W)(gzseek)(\W)/g,
				/(\W)(gztell)(\W)/g,
				/(\W)(gzwrite)(\W)/g,
				/(\W)(gzclose)(\W)/g,
				/(\W)(bzopen)(\W)/g,
				/(\W)(bzerrno)(\W)/g,
				/(\W)(bzerror)(\W)/g,
				/(\W)(bzerrstr)(\W)/g,
				/(\W)(bzflush)(\W)/g,
				/(\W)(bzread)(\W)/g,
				/(\W)(bzwrite)(\W)/g,
				/(\W)(bzclose)(\W)/g,
				/(\W)(com_load)(\W)/g,
				/(\W)(com_invoke)(\W)/g,
				/(\W)(com_propget)(\W)/g,
				/(\W)(com_get)(\W)/g,
				/(\W)(com_propput)(\W)/g,
				/(\W)(com_set)(\W)/g,
				/(\W)(com_propput)(\W)/g,
				/(\W)(imagecreate)(\W)/g,
				/(\W)(imagecreatefromgd)(\W)/g,
				/(\W)(imagecreatefromgd2)(\W)/g,
				/(\W)(imagecreatefromgd2part)(\W)/g,
				/(\W)(imagecreatefromgif)(\W)/g,
				/(\W)(imagecreatefromjpeg)(\W)/g,
				/(\W)(imagecreatefrompng)(\W)/g,
				/(\W)(imagecreatefromwbmp)(\W)/g,
				/(\W)(imagecreatefromstring)(\W)/g,
				/(\W)(imagecreatefromxbm)(\W)/g,
				/(\W)(imagecreatefromxpm)(\W)/g,
				/(\W)(imagecreatetruecolor)(\W)/g,
				/(\W)(imagerotate)(\W)/g,
				/(\W)(imagearc)(\W)/g,
				/(\W)(imagechar)(\W)/g,
				/(\W)(imagecharup)(\W)/g,
				/(\W)(imagecolorallocate)(\W)/g,
				/(\W)(imagecolorat)(\W)/g,
				/(\W)(imagecolorclosest)(\W)/g,
				/(\W)(imagecolorexact)(\W)/g,
				/(\W)(imagecolorresolve)(\W)/g,
				/(\W)(imagegammacorrect)(\W)/g,
				/(\W)(imagegammacorrect)(\W)/g,
				/(\W)(imagecolorset)(\W)/g,
				/(\W)(imagecolorsforindex)(\W)/g,
				/(\W)(imagecolorstotal)(\W)/g,
				/(\W)(imagecolortransparent)(\W)/g,
				/(\W)(imagecopy)(\W)/g,
				/(\W)(imagecopyresized)(\W)/g,
				/(\W)(imagedashedline)(\W)/g,
				/(\W)(imagefill)(\W)/g,
				/(\W)(imagefilledpolygon)(\W)/g,
				/(\W)(imagefilledrectangle)(\W)/g,
				/(\W)(imagefilltoborder)(\W)/g,
				/(\W)(imagegif)(\W)/g,
				/(\W)(imagepng)(\W)/g,
				/(\W)(imagejpeg)(\W)/g,
				/(\W)(imagewbmp)(\W)/g,
				/(\W)(imageinterlace)(\W)/g,
				/(\W)(imageline)(\W)/g,
				/(\W)(imagepolygon)(\W)/g,
				/(\W)(imagepstext)(\W)/g,
				/(\W)(imagerectangle)(\W)/g,
				/(\W)(imagerotate)(\W)/g,
				/(\W)(imagesetpixel)(\W)/g,
				/(\W)(imagestring)(\W)/g,
				/(\W)(imagestringup)(\W)/g,
				/(\W)(imagesx)(\W)/g,
				/(\W)(imagesy)(\W)/g,
				/(\W)(imagettftext)(\W)/g,
				/(\W)(imagefilledarc)(\W)/g,
				/(\W)(imageellipse)(\W)/g,
				/(\W)(imagefilledellipse)(\W)/g,
				/(\W)(imagecolorclosestalpha)(\W)/g,
				/(\W)(imagecolorexactalpha)(\W)/g,
				/(\W)(imagecolorresolvealpha)(\W)/g,
				/(\W)(imagecopymerge)(\W)/g,
				/(\W)(imagecopymergegray)(\W)/g,
				/(\W)(imagecopyresampled)(\W)/g,
				/(\W)(imagetruecolortopalette)(\W)/g,
				/(\W)(imagesetbrush)(\W)/g,
				/(\W)(imagesettile)(\W)/g,
				/(\W)(imagesetthickness)(\W)/g,
				/(\W)(image2wbmp)(\W)/g,
				/(\W)(imagealphablending)(\W)/g,
				/(\W)(imageantialias)(\W)/g,
				/(\W)(imagecolorallocatealpha)(\W)/g,
				/(\W)(imagecolorclosesthwb)(\W)/g,
				/(\W)(imagecolordeallocate)(\W)/g,
				/(\W)(imagecolormatch)(\W)/g,
				/(\W)(imagefilter)(\W)/g,
				/(\W)(imagefttext)(\W)/g,
				/(\W)(imagegd)(\W)/g,
				/(\W)(imagegd2)(\W)/g,
				/(\W)(imageistruecolor)(\W)/g,
				/(\W)(imagelayereffect)(\W)/g,
				/(\W)(imagepalettecopy)(\W)/g,
				/(\W)(imagesavealpha)(\W)/g,
				/(\W)(imagesetstyle)(\W)/g,
				/(\W)(imagexbm)(\W)/g,
				/(\W)(imagedestroy)(\W)/g,
				/(\W)(imageloadfont)(\W)/g,
				/(\W)(imagechar)(\W)/g,
				/(\W)(imagecharup)(\W)/g,
				/(\W)(imagefontheight)(\W)/g,
				/(\W)(imagepsloadfont)(\W)/g,
				/(\W)(imagepstext)(\W)/g,
				/(\W)(imagepsslantfont)(\W)/g,
				/(\W)(imagepsextendfont)(\W)/g,
				/(\W)(imagepsencodefont)(\W)/g,
				/(\W)(imagepsbbox)(\W)/g,
				/(\W)(imagepsfreefont)(\W)/g,
				/(\W)(curl_copy_handle)(\W)/g,
				/(\W)(curl_init)(\W)/g,
				/(\W)(curl_copy_handle)(\W)/g,
				/(\W)(curl_errno)(\W)/g,
				/(\W)(curl_error)(\W)/g,
				/(\W)(curl_exec)(\W)/g,
				/(\W)(curl_getinfo)(\W)/g,
				/(\W)(curl_setopt)(\W)/g,
				/(\W)(curl_close)(\W)/g,
				/(\W)(dba_open)(\W)/g,
				/(\W)(dba_delete)(\W)/g,
				/(\W)(dba_exists)(\W)/g,
				/(\W)(dba_fetch)(\W)/g,
				/(\W)(dba_firstkey)(\W)/g,
				/(\W)(dba_insert)(\W)/g,
				/(\W)(dba_nextkey)(\W)/g,
				/(\W)(dba_optimize)(\W)/g,
				/(\W)(dba_replace)(\W)/g,
				/(\W)(dba_sync)(\W)/g,
				/(\W)(dba_close)(\W)/g,
				/(\W)(dba_popen)(\W)/g,
				/(\W)(dba_delete)(\W)/g,
				/(\W)(dba_exists)(\W)/g,
				/(\W)(dba_fetch)(\W)/g,
				/(\W)(dba_firstkey)(\W)/g,
				/(\W)(dba_insert)(\W)/g,
				/(\W)(dba_nextkey)(\W)/g,
				/(\W)(dba_optimize)(\W)/g,
				/(\W)(dba_replace)(\W)/g,
				/(\W)(dba_sync)(\W)/g,
				/(\W)(strstr)(\W)/g,
				/(\W)(strtoupper)(\W)/g,
				/(\W)(strtolower)(\W)/g,
				/(\W)(strpos)(\W)/g,
				/(\W)(explode)(\W)/g,
				/(\W)(implode)(\W)/g,
				/(\W)(closedir)(\W)/g,
				/(\W)(getdir)(\W)/g,
				/(\W)(floatval)(\W)/g,
				/(\W)(rtrim)(\W)/g,
				/(\W)(fwrite)(\W)/g,
				/(\W)(extension_loaded)(\W)/g,
				/(\W)(final)(\W)/g,
				/(\W)(catch)(\W)/g,
				/(\W)(clone)(\W)/g,
				/(\W)(goto)(\W)/g,
				/(\W)(instanceof)(\W)/g,
				/(\W)(namespace)(\W)/g,
				/(\W)(throw)(\W)/g,
				/(\W)(try)(\W)/g,
				/(\W)(trigger_error)(\W)/g,
				/(\W)(ftp_connect)(\W)/g,
				/(\W)(ftp_ssl_connect)(\W)/g,
				/(\W)(ftp_close)(\W)/g,
				/(\W)(ftp_login)(\W)/g,
				/(\W)(ftp_pwd)(\W)/g,
				/(\W)(ftp_cdup)(\W)/g,
				/(\W)(ftp_chdir)(\W)/g,
				/(\W)(ftp_mkdir)(\W)/g,
				/(\W)(ftp_rmdir)(\W)/g,
				/(\W)(ftp_nlist)(\W)/g,
				/(\W)(ftp_rawlist)(\W)/g,
				/(\W)(ftp_systype)(\W)/g,
				/(\W)(ftp_pasv)(\W)/g,
				/(\W)(ftp_get)(\W)/g,
				/(\W)(ftp_fget)(\W)/g,
				/(\W)(ftp_put)(\W)/g,
				/(\W)(ftp_fput)(\W)/g,
				/(\W)(ftp_size)(\W)/g,
				/(\W)(ftp_mdtm)(\W)/g,
				/(\W)(ftp_rename)(\W)/g,
				/(\W)(ftp_delete)(\W)/g,
				/(\W)(ftp_site)(\W)/g,
				/(\W)(ftp_alloc)(\W)/g,
				/(\W)(ftp_chmod)(\W)/g,
				/(\W)(ftp_exec)(\W)/g,
				/(\W)(ftp_get_option)(\W)/g,
				/(\W)(ftp_nb_continue)(\W)/g,
				/(\W)(ftp_nb_fget)(\W)/g,
				/(\W)(ftp_nb_fput)(\W)/g,
				/(\W)(ftp_nb_get)(\W)/g,
				/(\W)(ftp_nb_put)(\W)/g,
				/(\W)(ftp_raw)(\W)/g,
				/(\W)(ftp_set_option)(\W)/g,
				/(\W)(imap_open)(\W)/g,
				/(\W)(imap_close)(\W)/g,
				/(\W)(imap_append)(\W)/g,
				/(\W)(imap_body)(\W)/g,
				/(\W)(imap_check)(\W)/g,
				/(\W)(imap_createmailbox)(\W)/g,
				/(\W)(imap_delete)(\W)/g,
				/(\W)(imap_deletemailbox)(\W)/g,
				/(\W)(imap_expunge)(\W)/g,
				/(\W)(imap_fetchbody)(\W)/g,
				/(\W)(imap_fetchstructure)(\W)/g,
				/(\W)(imap_headerinfo)(\W)/g,
				/(\W)(imap_header)(\W)/g,
				/(\W)(imap_headers)(\W)/g,
				/(\W)(imap_listmailbox)(\W)/g,
				/(\W)(imap_getmailboxes)(\W)/g,
				/(\W)(imap_get_quota)(\W)/g,
				/(\W)(imap_status)(\W)/g,
				/(\W)(imap_listsubscribed)(\W)/g,
				/(\W)(imap_set_quota)(\W)/g,
				/(\W)(imap_set_quota)(\W)/g,
				/(\W)(imap_getsubscribed)(\W)/g,
				/(\W)(imap_mail_copy)(\W)/g,
				/(\W)(imap_mail_move)(\W)/g,
				/(\W)(imap_num_msg)(\W)/g,
				/(\W)(imap_num_recent)(\W)/g,
				/(\W)(imap_ping)(\W)/g,
				/(\W)(imap_renamemailbox)(\W)/g,
				/(\W)(imap_reopen)(\W)/g,
				/(\W)(imap_subscribe)(\W)/g,
				/(\W)(imap_undelete)(\W)/g,
				/(\W)(imap_unsubscribe)(\W)/g,
				/(\W)(imap_scanmailbox)(\W)/g,
				/(\W)(imap_mailboxmsginfo)(\W)/g,
				/(\W)(imap_fetchheader)(\W)/g,
				/(\W)(imap_uid)(\W)/g,
				/(\W)(imap_msgno)(\W)/g,
				/(\W)(imap_search)(\W)/g,
				/(\W)(imap_fetch_overview)(\W)/g,
				/(\W)(array_change_key_case)(\W)/g,
				/(\W)(array_chunk)(\W)/g,
				/(\W)(array_combine)(\W)/g,
				/(\W)(array_count_values)(\W)/g,
				/(\W)(array_diff)(\W)/g,
				/(\W)(array_diff_assoc)(\W)/g,
				/(\W)(array_diff_key)(\W)/g,
				/(\W)(array_diff_uassoc)(\W)/g,
				/(\W)(array_diff_ukey)(\W)/g,
				/(\W)(array_fill)(\W)/g,
				/(\W)(array_fill_keys)(\W)/g,
				/(\W)(array_filter)(\W)/g,
				/(\W)(array_flip)(\W)/g,
				/(\W)(array_intersect)(\W)/g,
				/(\W)(array_intersect_assoc)(\W)/g,
				/(\W)(array_intersect_key)(\W)/g,
				/(\W)(array_intersect_uassoc)(\W)/g,
				/(\W)(array_intersect_ukey)(\W)/g,
				/(\W)(array_key_exists)(\W)/g,
				/(\W)(array_keys)(\W)/g,
				/(\W)(array_map)(\W)/g,
				/(\W)(array_merge)(\W)/g,
				/(\W)(array_merge_recursive)(\W)/g,
				/(\W)(array_multisort)(\W)/g,
				/(\W)(array_pad)(\W)/g,
				/(\W)(array_pop)(\W)/g,
				/(\W)(array_product)(\W)/g,
				/(\W)(array_push)(\W)/g,
				/(\W)(array_rand)(\W)/g,
				/(\W)(array_reduce)(\W)/g,
				/(\W)(array_replace)(\W)/g,
				/(\W)(array_replace_recursive)(\W)/g,
				/(\W)(array_reverse)(\W)/g,
				/(\W)(array_search)(\W)/g,
				/(\W)(array_shift)(\W)/g,
				/(\W)(array_slice)(\W)/g,
				/(\W)(array_splice)(\W)/g,
				/(\W)(array_sum)(\W)/g,
				/(\W)(array_udiff)(\W)/g,
				/(\W)(array_udiff_assoc)(\W)/g,
				/(\W)(array_udiff_uassoc)(\W)/g,
				/(\W)(array_uintersect)(\W)/g,
				/(\W)(array_uintersect_assoc)(\W)/g,
				/(\W)(array_uintersect_uassoc)(\W)/g,
				/(\W)(array_unique)(\W)/g,
				/(\W)(array_unshift)(\W)/g,
				/(\W)(array_values)(\W)/g,
				/(\W)(array_walk)(\W)/g,
				/(\W)(array_walk_recursive)(\W)/g,
				/(\W)(arrayaccess)(\W)/g,
				/(\W)(arrayiterator)(\W)/g,
				/(\W)(arrayobject)(\W)/g,
				/(\W)(fclose)(\W)/g,
				/(\W)(flock)(\W)/g,
				/(\W)(floor)(\W)/g,
				/(\W)(flush)(\W)/g,
				/(\W)(fmod)(\W)/g,
				/(\W)(fnmatch)(\W)/g,
				/(\W)(fopen)(\W)/g,
				/(\W)(fpassthru)(\W)/g,
				/(\W)(fprintf)(\W)/g,
				/(\W)(fputcsv)(\W)/g,
				/(\W)(fputs)(\W)/g,
				/(\W)(fread)(\W)/g,
				/(\W)(fscanf)(\W)/g,
				/(\W)(fseek)(\W)/g,
				/(\W)(fsockopen)(\W)/g,
				/(\W)(fstat)(\W)/g,
				/(\W)(ftell)(\W)/g,
				/(\W)(__construct)(\W)/g,
				/(\W)(__destruct)(\W)/g
			];
			
			result = result.replace(/</g, '&lt;');
			result = result.replace(/>/g, '&gt;');
			
			console.log(result);
			result = result.replace(stringRegex1, '$1<span class="phpString">$2</span>');
			console.log(result);
			result = result.replace(stringRegex2, '$1<span class="phpString">$2</span>');
			console.log(result);
			
			for(var i = 0; i < phpKeywords.length && i <= 1000; i++) {
				result = result.replace(phpKeywords[i], '$1<span class="phpOperator">$2</span>$3');
			}
			
			result = result.replace(intRegex, '$1<span class="phpInt">$2</span>$3');
			result = result.replace(phpStartRegex, '<span class="phpStart">$1</span>');
			result = result.replace(phpEndRegex, '<span class="phpEnd">$1</span>');
			result = result.replace(phpVarRegex, '<span class="phpVar">$1</span>');
			result = result.replace(commentRegex1, '<span class="comment">$1</span>');
			result = result.replace(commentRegex2, '<span class="comment">$1</span>');
			
			result = result.replace(/\n/g, '<br />');
			result = result.replace(/\t/g, '&nbsp;&nbsp;&nbsp;&nbsp;');
			
			return result;
		}
	};
	switch(codeType.toLowerCase()) {
		case 'html':
			var result = functions.html();
			self.html(result);
			break;
		case 'css':
			var result = functions.css();
			self.html(result);
			break;
		case 'js':
			var result = functions.js();
			self.html(result);
			break;
		case 'php':
			var result = functions.php();
			self.html(result);
			break;
	};
};
